USE [master]
GO

/****** Object:  Database [MaidInIndia]    Script Date: 7/25/2020 5:11:41 PM ******/
CREATE DATABASE [MaidInIndia]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MaidInIndia', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MaidInIndia.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MaidInIndia_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\MaidInIndia_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MaidInIndia] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MaidInIndia].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MaidInIndia] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MaidInIndia] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MaidInIndia] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MaidInIndia] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MaidInIndia] SET ARITHABORT OFF 
GO

ALTER DATABASE [MaidInIndia] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MaidInIndia] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MaidInIndia] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MaidInIndia] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MaidInIndia] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MaidInIndia] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MaidInIndia] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MaidInIndia] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MaidInIndia] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MaidInIndia] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MaidInIndia] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MaidInIndia] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MaidInIndia] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MaidInIndia] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MaidInIndia] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MaidInIndia] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MaidInIndia] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MaidInIndia] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MaidInIndia] SET  MULTI_USER 
GO

ALTER DATABASE [MaidInIndia] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MaidInIndia] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MaidInIndia] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MaidInIndia] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MaidInIndia] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MaidInIndia] SET  READ_WRITE 
GO

